### PR TITLE
Changed to asynchronous initialization API

### PR DESCRIPTION
**Pull request by MarcKamradt**

### CODE REVIEW

**Comment by OWIAdmin** [comment]
Thank you so much for taking the time to try and figure this out.  I think I tried some of these things a couple of months ago but then it broke compatibility with VS2015 or maybe it stopped even working in VS2017.  Anyhow, I'll take a look at it in more depth once I make it a higher priority.

Thanks so much for your time and contribution though, I really appreciate it!

**Comment by korypostma** [comment]
Thank you so much for taking the time to try and figure this out. I think I tried some of these things a couple of months ago but then it broke compatibility with VS2015 or maybe it stopped even working in VS2017. Anyhow, I'll take a look at it in more depth once I make it a higher priority.

Thanks so much for your time and contribution though, I really appreciate it!

**Comment by MarcKamradt** [comment]
As far as I know the API has been introduced in VS 2015 but I did not do any testing besides VS 2019. Maybe it can at least be for your reference.

For the time being I put up a binary release here:

https://github.com/MarcKamradt/BlackSpace/releases

**Comment by Toddler-Boy** [comment]
Can you please test this and accept this pull request?

**Comment by korypostma** [comment]
Basically similar commit here: https://github.com/korypostma/BlackSpace/commit/40f6852016e5086eb23eee98cdc9ce2433905be3

**Pull request closed without merging**
